### ISSUE TITLE
New Azure Function for Polling an endpoint

### ISSUE THREAD

**Issue by nastassiar** [jefking/FunctionLibrary#52]
If you'd like to submit a Repo to the Azure Serverless Community Library, fill out the following template:

- Title: PollingWithDuplicateCheck
________

- Description: A short block of text (~100 characters max) explaining what your sample does.
Triggered every 5 minutes to do a GET from an API, check for duplicated records in Azure blob storage it has already seen and POST any new alerts to another API.
________

- Template: The path to the ARM template which deploys the application. For more information, see the [README](https://github.com/Azure/FunctionLibrary/blob/master/README.md).

https://github.com/nastassiar/WebRequestFunction/blob/master/azuredeploy.json
________

- Repository: The URL of a public git repository.
https://github.com/nastassiar/WebRequestFunction
________

- Language (optional): The language your code is written in (Functions only.)
C#
________

- Technology (optional): Whether your app is a Function App or a Logic App
Function App
________

- Solution Area (optional): A broad level categorization of what type of solution you've built (IoT, ML, Data Processing, ...)
________

**Comment by fashaikh** [comment]
Thanks @nastassiar ! This has been integrated. Will update when the deployment happens.
